language: node_js
sudo: false
node_js: 8
cache:
  directories:
    - node_modules
  before_script:
    - node --version
    - npm --version
  script:
    - npm run lint
    - npm run test
  before_deploy:
    - npm install
